### PR TITLE
OPTIM: merge data transfers. part 1

### PR DESCRIPTION
**Pull request by arom4github**
some data transfers are merged into a single one

### CODE REVIEW

**Comment by biochem-fan** [comment]
Thanks for contribution. What does "part 1" mean? If more commits are expected on this "merge data transfer" line, I would like to wait for them before starting testing within LMB.

**Comment by arom4github** [comment]
I was informed that you prefer to have a minimal amount of modifications per pull request.  
That's why I planned to send yet three pull request similar to this. If you prefer, I can merge them into one and send them at once.

**Comment by biochem-fan** [comment]
OK, probably I was not clear enough.

I don't like "squash merge" as I want to keep records of changes, but I prefer pull request to be grouped by logical blocks. In this case, please keep three commits as they are, but make only one pull request.

If you have done some tests (in terms of result or speed) on your side, please describe it as well.

**Comment by arom4github** [comment]
Here they are.

The result is the same.

**Comment by biochem-fan** [comment]
Thanks. We will test this next week. If we don't reply by the end of the next week, please remind us again.

**Comment by biochem-fan** [comment]
I merged your contribution to our `nv-optim-datatransfer` branch. We will test this and then merge into the `ver3.1` branch.

**Comment by biochem-fan** [comment]
Merged into `ver3.1`.

**Pull request merged**
