### PR TITLE
Ver5.0 HIP Fixes

### PR DESCRIPTION
**Pull request by suyashtn**
Minor updates to: 
* CMake config to correctly identify the HIP path
* `src/acc/hip/` files update paths of HIP lib headers (`'hipfft.h`, `hiprand.h`, `hipcub`)
These updates are required to ensure compatibility with newer ROCm > 5.7 and support on latest AMD Instinct GPUs.

### CODE REVIEW

**Comment by biochem-fan** [comment]
Thank you very much for your contribution.

> ensure compatibility with newer ROCm > 5.7 and support on latest AMD Instinct GPUs

After this change, is the code still compatible with older ROCm and older GPUs?

**Comment by suyashtn** [comment]
Hi @biochem-fan , yes, the proposed changes extend the support for new ROCm on latest Instinct GPUs and keeps the functionality on previously supported GPUs intact.

**Comment by biochem-fan** [comment]
> keeps the functionality on previously supported GPUs intact

Let me clarify my question with a concrete example:

You changed the include path from `hipfft.h` to `hipfft/hipfft.h`.
Are users of older ROCm (<= 5.7) still able to compile the code? Or should we ask users to upgrade ROCm to > 5.7?

**Comment by suyashtn** [comment]
Apologies for the delay @biochem-fan! The path change from `hipfft.h` to `hipfft/hipfft.h` is valid for ROCm >= 5.2. Between ROCm 5.2 and 5.7, the` include/` in ROCm was configured to find these headers regardless, however in newer ROCm > 5.7, the headers are only found inside a particular path (more stringent). HIP support in RELION requires min. ROCm 5.3, hence this change should not affect users with ROCm < 5.7!

**Comment by biochem-fan** [comment]
@suyashtn Thank you very much for clarification. I merged your contribution.

**Pull request merged**
